### ISSUE TITLE
Strange dates in the generated zip

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/code.quarkus.io#345]
**Describe the bug**

So I generated a new project (on April 24th) but was surprised my files were dated April 22th on my disk. Then looked at the generated ZIP and turns out the date was the same (Apr 22th).

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Date should be the generation date, no ? Thus Apr 24th in this case ?

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Date is Apr 22th

**To Reproduce**
1. go to code.quarkus.io
2. look at the generated zip
3. 

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser: Firefox
 - OS: Win10

**Additional context**
(Add any other context about the problem here.)

**Comment by ia3andy** [comment]
Hey @jeffmaury,

This is due to a workaround. We had problem with files being created in the future in some location. The file are generated by the server which is not aware of the user location:
https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/kotlin/io/quarkus/code/misc/CommonsZipProjectWriter.java#L28

**Comment by jeffmaury** [comment]
Seems the comment needs an update 😁
