### ISSUE TITLE
GroupId as base-package of application

### ISSUE THREAD

**Issue by tacsio** [quarkusio/code.quarkus.io#405]
When creating a project using code.quarkus.io the base package of the application is always `org.acme`, even when the user defines his own groupId.

Using the Maven plugin, the base package is configured based on the projectGroupId.

```
mvn io.quarkus:quarkus-maven-plugin:1.9.1.Final:create \
    -DprojectGroupId=my.custom \
    -DprojectArtifactId=my-artifactId \
    -DprojectVersion=my-version \
    -DclassName="MyResource"
```

Is it possible to parametrize the 'package-name' key in the codestart.yml file?
```yml
language:
  base:
    data:
      resource: ...
      package-name: org.acme.resteasy
```

This way we could configure CodestartProject with the groupId defined by user.

https://github.com/quarkusio/quarkus/blob/4f3e17a7b8077fa07f598390154300a8a2191f8c/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/CreateProjectCommandHandler.java#L91-L92

**Comment by ia3andy** [comment]
Hi @tacsio,

We made the package name property work only RESTEasy and SpringWeb in the maven plugin for backward compatibility with the guides. We now have multiple examples (more are coming) and we want to avoid conflicts between them. We made the choice to make it hard coded because:
- each example has his own distinct package, so making it parametrized would make it hard to use and understand
- we can't keep a field in the UI which work only with some examples but not the others
- it's easier to rename/delete the example packages if it's always the same `org.acme.*`

The `group-id` is still used for the maven/gradle project config.

Do you have a particular use-case where it affects your work?

FYI, you can still use `c` and `p` if using the code.quarkus.io/api, but it's only work with RESTEasy and SpringWeb:
https://editor.swagger.io/?url=https://code.quarkus.io/openapi

![image](https://user-images.githubusercontent.com/2223984/97681553-3024c780-1a98-11eb-944a-3da0700af515.png)

**Comment by tacsio** [comment]
Thanks @ia3andy,

As you said, it's easier to rename/delete the example packages! 
I was just trying to understand why the behavior was a little different.

code.quarkus.io/api worked fine,
Thanks!!!!

**Comment by ia3andy** [comment]
@tacsio I have a good new :) we finally decided to keep that feature, the group-id will be used as package name :) for now it is only working with the RESTEasy and the Spring Web extensions, but this will soon be working with all different examples..

**Comment by tacsio** [comment]
That's great!!!
Please let me know if I can be of any help.

Thanks for the reply!
