### ISSUE TITLE
Should or should not keep the list of selected extensions always visible (like before)

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/code.quarkus.io#486]
I don't really like the new layout of code.quarkus.io. I don't like how it doesn't show me what extensions i've selected and keep that list displayed all the time. I have to manually move my mouse up to the spaceship and hover over instead of just having them displayed on the screen.

This means I need to take my hands off the keyboard and move my mouse up there to see what extensions I've currently selected.

I feel there is a ton of wasted space on the screen.

![code quarkus io1](https://user-images.githubusercontent.com/363447/125116586-f0988b80-e0ba-11eb-90d8-e7102d1ee841.png)

Now that the descriptions of the extensions are under the titles (which I really like!), you could move the list of extensions over to the right and put the list of selected extensions, along with the search bar, on the left, like it used to be in previous versions. The search bar doesn't need to be that big either.

**Comment by ia3andy** [comment]
I agree there is way too much free space. IMO, it's mostly due to the fact that our description for extensions is really poor for most of them.. When you look at extension with a nice description, this doesn't feel "as bad":
![image](https://user-images.githubusercontent.com/2223984/125125589-109b6f80-e0fa-11eb-8ba8-5a07dce56553.png)


That being said, this new design is preparing some future changes and no worries this space is not going to stay empty!

**Comment by edeandrea** [comment]
Thanks @ia3andy for the update! It would still be nice for the currently selected extensions to be displayed on the page somewhere rather than me having to use the mouse to hover to see.

**Comment by ia3andy** [comment]
@edeandrea we will see how user interact this "cart" extension view, it has many advantages:
- we have new free space to use for something else :)
- when arriving on the page it's not very nice to have an empty selection list taking a whole column
- the app you are generating is fully described in the top bar going from left to right
- we have more space to improve our search experience (https://github.com/quarkusio/code.quarkus.io/issues/459)
- you already have selected extensions as part of the list with the checkboxes, the extension selection view is redundant but it helps have an overview of what you wish to generate
- it appears when you select new extensions so that you keep seeing your list evolving (we may improve the delay and make it disappear on scroll https://github.com/quarkusio/code.quarkus.io/issues/482)
- as you said you can always check it just by moving your mouse over it before hitting "generate"


Also we may use that new free space column to introduce some "pre-selection" boxes to pre-select relevant set of extensions.

If we get many complaints, we will make that list fixed again..

**Comment by edeandrea** [comment]
> as you said you can always check it just by moving your mouse over it before hitting "generate"

That's my point. I don't want to have to take my hands off the keyboard. When I'm using it I'm just typing in the search, then tabbing and using the space bar to select things. I don't want to have to take my hands off the keyboard to see what extensions I've already selected. I want to see the list right there on the screen.

**Comment by ia3andy** [comment]
> > as you said you can always check it just by moving your mouse over it before hitting "generate"
> 
> That's my point. I don't want to have to take my hands off the keyboard. When I'm using it I'm just typing in the search, then tabbing and using the space bar to select things. I don't want to have to take my hands off the keyboard and have to use the mouse to see what extensions I've already selected. I want to see the list right there on the screen.
> 
> I do like the descriptions under the extension name.

@edeandrea you can use the search bar then arrows and space to select extensions, esc to clear the search. The last release really improved that experience btw.. also the rocket cart is automatically appearing each time you pick an extension so I don't see how it is a problem (and when you say you need to move the mouse). Maybe it's not working well on your browser?

Btw I just notice "alt + enter" is not working anymore, I need to fix that.

**Comment by edeandrea** [comment]
Thanks for all the tips but I'll keep my opinion that I'd prefer the list of selected extensions to be static and always visible. Just my opinion:)
