### ISSUE TITLE
Add Java version picker

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#595]
**Description**
I believe it would be a good addition

**Comment by maxandersen** [comment]
What would it do?

**Comment by rkraneis** [comment]
As long as Mandrel does not support Java 17, I would not enable this as a selectable option, as it complicates native compilation. Those users who then figure out how to build with GraalVM instead of Mandrel will also be able to figure out how to change the Java version ... (using Quarkus native on 17 myself).

**Comment by maxandersen** [comment]
We can always mark it as experimental so I would not let mandrelissues  be a blocker for this one. 

But I also don't think we should add this as code quarkus feature - it needs to be part of quarkus devtools which would take care of maven/Gradle/dockerfile differences.

**Comment by JurrianFahner** [comment]
Not everyone generates quarkus projects on the website directly. Today I created from Intellij directly (it uses the code.quarkus.io site to create the forms in intellij). 

I was surprised to learn that it was on java 11, because I expected java 17 (this LTS java version is GA since september already). 

In my case I would like to use the JEP359 (`record` classes).

To have a choice as a quarkus with the warning that I make an experimental choice seems for me a perfect solution. It's up  to the user whether experimental is acceptable.

**Comment by ia3andy** [comment]
We have an ongoing effort for this:
https://github.com/quarkusio/quarkus/pull/20849

As soon as it's available, we will add the java version picker on code.quarkus.io (and its API)

**Comment by ia3andy** [comment]
> But I also don't think we should add this as code quarkus feature - it needs to be part of quarkus devtools which would take care of maven/Gradle/dockerfile differences.

On the other command line tools, it uses the current java version. From code.quarkus.io and IDEs we need a picker for this obviously.

**Comment by ia3andy** [comment]
I added a feature request for this to also be a parameter in the command line tooling https://github.com/quarkusio/quarkus/issues/21629

**Comment by maxandersen** [comment]
> As soon as it's available, we will add the java version picker (8, 11, 17) on code.quarkus.io (and its API)

Quarkus 2 does not support Java 8 this I assume you mean just 11 and 17 :)

**Comment by ia3andy** [comment]
I didn't know we dropped support for it, maybe we should disable it in the generator then..

**Comment by ia3andy** [comment]
This is done
